[package]
name = "charset_to_img"
authors = ["Calum Chisholm"]
edition = "2021"
version = "0.1.0"

[dependencies]
structopt = { version = "0.3.26", default-features = false }
image = { version = "0.25.5", default-features = false, features = [ "png", "gif" ] }